### ISSUE TITLE
兄弟，你用的 ssrlibv库是哪个？

### ISSUE THREAD

**Issue by Daopr** [techotaku/Docker-LEDE-SDK#1]
我这边用的[https://github.com/AlexZhuo/openwrt-shadowsocksr](https://github.com/AlexZhuo/openwrt-shadowsocksr)，但好像对不上号，麻烦给个你用的连接

**Comment by techotaku** [comment]
不确定你说的对不上号是啥意思……SDK这个库，跟ss/ssr并没有关系。    
P.S. Alex那个库应该是可以用的。如果你要原版的话，找了个社区的备份 https://github.com/shadowsocksr-rm/openwrt-shadowsocksr 。
